# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14KNh7D8WuRkPSVmkWp-hoPwixwwFMjDU
"""

import os
import io
import asyncio
import requests
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime
from time import sleep

import discord
from discord import app_commands
from discord.ext import commands
from dotenv import load_dotenv

# Load keys from environment variables (how real cloud hosts manage secrets)
load_dotenv()
DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
API_KEY = os.getenv("ROBLOX_API_KEY")

OPEN_CLOUD_BASE = "https://apis.roblox.com/cloud/v2"
OPEN_CLOUD_HEADERS = {"x-api-key": API_KEY}


# ============================================================
#  ROBLOX HELPER FUNCTIONS
# ============================================================

def get_user_id_from_username(username: str) -> str:
    url = "https://users.roblox.com/v1/usernames/users"
    response = requests.post(url, json={"usernames": [username]}, timeout=10)
    data = response.json()
    if response.status_code == 200 and data.get("data"):
        return str(data["data"][0]["id"])
    raise ValueError(f"Could not find Roblox user ID for **{username}**.")


def check_can_view_inventory(user_id: str) -> bool:
    url = f"{OPEN_CLOUD_BASE}/users/{user_id}/inventory-items"
    params = {"filter": "badges=true", "maxPageSize": 1}
    response = requests.get(url, headers=OPEN_CLOUD_HEADERS, params=params, timeout=10)
    if response.status_code == 403:
        return False
    if response.status_code == 200:
        return True
    response.raise_for_status()
    return False


def fetch_badges_open_cloud(user_id: str) -> list[dict]:
    url = f"{OPEN_CLOUD_BASE}/users/{user_id}/inventory-items"
    params = {"filter": "badges=true", "maxPageSize": 100}
    badges = []
    page_token = None

    while True:
        if page_token:
            params["pageToken"] = page_token

        response = requests.get(url, headers=OPEN_CLOUD_HEADERS, params=params, timeout=10)

        # Handle rate limits
        retry_after = 5
        while response.status_code == 429:
            sleep(retry_after)
            response = requests.get(url, headers=OPEN_CLOUD_HEADERS, params=params, timeout=10)
            retry_after += 5

        response.raise_for_status()
        data = response.json()

        for item in data.get("inventoryItems", []):
            badges.append(item)

        page_token = data.get("nextPageToken")
        if not page_token:
            break

    return badges


def convert_date_to_datetime(date: str) -> datetime:
    if "." in date:
        base, frac = date.rstrip("Z").split(".", 1)
        frac = (frac + "000")[:3]
        date = f"{base}.{frac}Z"
    else:
        date = date.rstrip("Z") + ".000Z"
    return datetime.strptime(date, "%Y-%m-%dT%H:%M:%S.%fZ")


def generate_badge_plot(username: str, user_id: str, dates: list[str]) -> io.BytesIO:
    parsed = sorted(convert_date_to_datetime(d) for d in dates)
    cumulative_counts = list(range(1, len(parsed) + 1))

    plt.style.use("dark_background")
    fig, ax = plt.subplots(figsize=(8, 5))

    ax.scatter(parsed, cumulative_counts, marker="o", alpha=0.2, color="#00a2ff", s=15)
    ax.set_xlabel("Badge Earned Date")
    ax.set_ylabel("Total Badges")
    ax.set_title(f"Badges over Time for {username} ({user_id})")
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    ax.xaxis.set_major_locator(mdates.YearLocator())

    ax.text(
        0.05, 0.95,
        f"Badge Count: {len(parsed)}",
        ha="left", va="top", color="white",
        transform=ax.transAxes,
    )
    plt.tight_layout()

    buffer = io.BytesIO()
    plt.savefig(buffer, format="png", bbox_inches="tight", dpi=150)
    buffer.seek(0)
    plt.close(fig)
    return buffer


def process_roblox_user(username: str):
    user_id = get_user_id_from_username(username)

    if not check_can_view_inventory(user_id):
        raise PermissionError(
            f"**{username}**'s inventory is private. They must set their inventory to public to generate this plot."
        )

    badges = fetch_badges_open_cloud(user_id)
    dates = [item["addTime"] for item in badges if "addTime" in item]

    if not dates:
        raise ValueError(f"No badge history found for **{username}**.")

    buffer = generate_badge_plot(username, user_id, dates)
    return buffer, len(dates), user_id


# ============================================================
#  DISCORD BOT SETUP
# ============================================================

class BadgeBot(commands.Bot):
    def __init__(self):
        intents = discord.Intents.default()
        super().__init__(command_prefix="!", intents=intents)

    async def setup_hook(self):
        await self.tree.sync()
        print("Slash commands synced successfully!")

bot = BadgeBot()

@bot.event
async def on_ready():
    print(f"Logged in as {bot.user} (ID: {bot.user.id})")


@bot.tree.command(name="badges", description="Generate a cumulative badge graph for a Roblox user.")
@app_commands.describe(username="The Roblox username to inspect")
async def badges(interaction: discord.Interaction, username: str):
    await interaction.response.defer(thinking=True)

    try:
        buffer, count, user_id = await asyncio.to_thread(process_roblox_user, username)

        file = discord.File(fp=buffer, filename=f"{username}_badges.png")

        embed = discord.Embed(
            title=f"Badge History — {username}",
            description=f"**User ID:** {user_id}\n**Total Badges Tracked:** {count:,}",
            color=discord.Color.blue()
        )
        embed.set_image(url=f"attachment://{username}_badges.png")

        await interaction.followup.send(embed=embed, file=file)

    except PermissionError as pe:
        await interaction.followup.send(content=f"🔒 {str(pe)}")
    except ValueError as ve:
        await interaction.followup.send(content=f"⚠️ {str(ve)}")
    except Exception as e:
        await interaction.followup.send(content=f"❌ An error occurred: `{str(e)}`")


if __name__ == "__main__":
    bot.run(DISCORD_TOKEN)